name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'
          
      - run: dotnet test PereViader.Utils.Common
      - run: dotnet build PereViader.Utils.Common --configuration Release
      
      - name: Publish Common
        uses: tedd/publish-nuget-neo@v1
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PROJECT_FILE_PATH: PereViader.Utils.Common/PereViader.Utils.Common/PereViader.Utils.Common.csproj
          REBUILD_PROJECT: false

      - name: Publish Generators
        uses: tedd/publish-nuget-neo@v1
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PROJECT_FILE_PATH: PereViader.Utils.Common/PereViader.Utils.Common.Generators/PereViader.Utils.Common.Generators.csproj
          REBUILD_PROJECT: false