name: Publish Unity3d Package
on: 
  workflow_call:
      
env:
  version_file: PereViader.Utils.Common/PereViader.Utils.Common/PereViader.Utils.Common.csproj

jobs:
  PublishUnity3dPackage:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - id: get-version
        run: |
          version=$(grep -oP '(?<=<Version>)[^<]+' "${{ env.version_file }}")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: release-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_exists=$(gh release view "Unity3d/${{ steps.get-version.outputs.version }}" &> /dev/null && echo "true" || echo "false")
          echo "Release exists $release_exists"
          echo "exists=$release_exists" >> $GITHUB_OUTPUT

      - name: Create Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          sh ./PereViader.Utils.Unity3d/Assets/Tools/GeneratePackage.sh

      - name: Create github release
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Unity3d/${{ steps.get-version.outputs.version }}
          name: PereViader.Utils.Unity3d ${{ steps.get-version.outputs.version }}
          files: |
            UnityPackageRelease/com.pereviader.utils.unity3d-${{ steps.get-version.outputs.version }}.tgz