name: Test Unity3d
on: 
  workflow_call:

jobs:
  TestUnity3d:
    permissions:
      contents: read
      checks: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - run: sh ./PereViader.Utils.Unity3d/Assets/Tools/UpdateUtilsDll.sh

      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "PereViader.Utils.Unity3d"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
