name: Test Common

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  TestCommon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'
          
      - run: dotnet test PereViader.Utils.Common