name: Test and publish
on: 
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
    TestCommon:
      uses: ./.github/workflows/TestCommon.yml
      secrets: inherit
    
    TestUnity3d:
      uses: ./.github/workflows/TestUnity3d.yml
      secrets: inherit
      permissions:
        contents: read
        checks: write
    
    PublishNugetPackage:
      needs: [TestCommon, TestUnity3d]
      uses: ./.github/workflows/PublishNugetPackage.yml
      secrets: inherit
    
    PublishUnity3dPackage:
      needs: [TestCommon, TestUnity3d]
      uses: ./.github/workflows/PublishUnity3dPackage.yml
      secrets: inherit
      permissions:
        contents: write